fonts:
  base: '"Noto Sans CJK JP", sans-serif'
  code: '"Consolas", "Source Han Code JP", monospace'

colors:
  master_accent: "#ff715e"
  master_background: "#beb9ad"
  master_text: "#111111"
  master_divider: "#999999"

  link_text: "#555555"

  stripe_background1: "#111111"
  stripe_background2: "#333333"
  stripe_text: "#beb9ad"

  site_header_title_text: "#111111"

  container_background: "#f2f2f2"

  code_background: "#f2f2f2"
  code_text: "red"
  code_block_background: "#111111"
  code_block_text: "#dddddd"

  table_header_background: "#999999"
  table_background: "#beb9ad"
  table_border: "#111111"

images:
  default_thumbnail: "/static/images/default-thumbnail.png"
