fonts:
  base: '"Noto Sans CJK JP", sans-serif'
  code: '"Consolas", "Source Han Code JP", monospace'

colors:
  primary: "#ff3344"
  background: "#ffebeb"
  text: "#111111"
  parent_card_background: "#ffffff"
  code_inline_background: "#f2f2f2"
  code_inline_text: "red"
  code_block_background: "#111111"
  code_block_text: "#dddddd"

images:
  default_thumbnail: "/static/images/default-thumbnail.png"

layout:
  max_width: "720px"
  border_radius: "8px"
