fonts:
  base: '"Noto Sans CJK JP", sans-serif'
  code: '"Consolas", "Source Han Code JP", monospace'

colors:
  primary: "#ff3344"

  background: "#ffebeb"
  text: "#111111"

  code_background: "#f2f2f2"
  code_text: "red"
  code_block_background: "#111111"
  code_block_text: "#dddddd"

  site_header_background: "#ffffff"
  site_header_nav_link_text: "#333333"

images:
  default_thumbnail: "/static/images/default-thumbnail.png"

layout:
  max_width: "720px"
  border_radius: "8px"
